import type { MasteryGroup } from "@/types";

export const SKILL_MASTERY: MasteryGroup[] = [
  {
    level: "Expert",
    description: "Ship production code daily",
    skills: [
      "React.js",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "GraphQL",
      "REST API",
      "Tailwind CSS",
      "Git",
      "CI/CD",
      "System Design",
    ],
  },
  {
    level: "Proficient",
    description: "Comfortable in complex projects",
    skills: [
      "AWS",
      "Docker",
      "Kubernetes",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Firebase",
      "Python",
      "GoLang",
      "Vue.js",
      "Angular",
      "Redux",
      "Express.js",
      "Microservices",
      "Elasticsearch",
      "Terraform",
      "LangChain",
      "OpenAI API",
      "Azure",
      "GCP",
      "Linux",
    ],
  },
  {
    level: "Familiar",
    description: "Explored in projects & research",
    skills: [
      "Java",
      "Ruby on Rails",
      "Flutter",
      "Electron",
      "Cassandra",
      "DynamoDB",
      "Cypress",
      "Playwright",
      "Vitest",
      "Strapi",
      "HeadlessCMS",
      "Web3.js",
      "Solidity",
      "Ethers.js",
      "IPFS",
      "PyTorch",
      "TensorFlow",
      "C/C++",
      "Serverless",
    ],
  },
];

export const ALL_TECHNOLOGIES = [
  "React", "TypeScript", "Next.js", "Node.js", "GraphQL", "REST API",
  "AWS", "Docker", "Kubernetes", "PostgreSQL", "MongoDB", "Redis",
  "GoLang", "Python", "Vue.js", "Angular", "Express.js", "Firebase",
  "Elasticsearch", "Terraform", "CI/CD", "Microservices", "System Design",
  "Agile", "TDD", "Linux", "Git", "Azure", "GCP", "LangChain",
  "OpenAI API", "Solidity", "Web3.js", "IPFS", "Flutter", "Cypress",
  "Playwright", "Vitest", "Strapi", "HeadlessCMS", "GenAI / LLMs",
] as const;
